{{- if .Values.mongo.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-mongo-0
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-mongo-1
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-mongo-2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongo.resources.requests.storage }}
---
{{- end }}
{{- if .Values.solr.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr-data-pvc-solr-0
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.solr.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr-data-pvc-solr-1
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.solr.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr-data-pvc-solr-2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.solr.resources.requests.storage }}

---
{{- end }}
{{- if .Values.zk.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-data-pvc-zookeeper-0
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.zk.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-data-pvc-zookeeper-1
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.zk.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-data-pvc-zookeeper-2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.zk.resources.requests.storage }}
---
{{- end }}
{{- if .Values.es.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-backup
  labels:
    component: elasticsearch
    role: es-pvc-backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-data-0
  labels:
    component: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-data-1
  labels:
    component: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es.resources.requests.storage }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: es-pvc-es-data-2
  labels:
    component: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.es.resources.requests.storage }}
---
{{- end }}
{{- if .Values.customizer.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: customizernfsclaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.customizer.resources.requests.storage }}
---
{{- end }}
