apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kudos-boards-minio-claim 
  namespace: connections
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: aws-efs

