apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-11-14T13:30:44Z
  labels:
    app: appregistry-client
    hostname: appregistry-client
  name: appregistry-client
  namespace: connections
  resourceVersion: "14988"
  selfLink: /api/v1/namespaces/connections/services/appregistry-client
  uid: 7cdd3769-e811-11e8-8437-b6aa278fd59f
spec:
  clusterIP: 10.0.70.191
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30285
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: appregistry-client
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
