apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customizernfsclaim
  namespace: connections
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: azurefile

