apiVersion: v1
kind: Service
metadata:
  labels:
    app: community-suggestions
  name: community-suggestions-lb
  namespace: connections
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: comm-suggest
    port: 32200 
    protocol: TCP
    targetPort: 3000 
  selector:
    name: community-suggestions
  type: LoadBalancer 
