apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: filebrowser 
    app.kubernetes.io/name: filebrowser
  name: filebrowser-lb
  namespace: connections
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 31675
    protocol: TCP
    targetPort: 80 
  selector:
    app.kubernetes.io/instance: filebrowser
    app.kubernetes.io/name: filebrowser 
  type: LoadBalancer 
