apiVersion: v1
kind: Service
metadata:
  labels:
    app: haproxy-redis
  name: haproxy-redis-lb
  namespace: connections
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: haproxy-redis
    port: 30379
    protocol: TCP
    targetPort: 6379 
  selector:
    name: haproxy
  type: LoadBalancer 
