apiVersion: v1
kind: Service
metadata:
  labels:
    app: mw-proxy-app
  name: mw-proxy-lb
  namespace: connections
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 30301
    protocol: TCP
    targetPort: 3000 
  selector:
    name: mw-proxy
  type: LoadBalancer 
